[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x1a48bf9f09dbc6a3bcbc1a70dc32db749a4f1913045fb9fa1b2ee1b25554093e'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]